### ISSUE TITLE
Found '%s' in service description

### ISSUE THREAD

**Issue by andrea-mattioli** [matoH12/checkmk-shelly-em#1]
Hi i receive this error:

An error occurred: Error creating configuration: Found '%s' in service description (Host: shelly-cucina, Check plugin: shelly_power, Item: None). Please try to rediscover the service to fix this issue

I miss something?

**Comment by matoH12** [comment]
Hi, 

1) in operating system you need install via PIP package "requests"  this is important 
2) what version of check_mk we are use ? 
3) so for good understanding can you send print-screen from error in check_mk ?

**Comment by andrea-mattioli** [comment]
Hi on OMD env requests is present:

```
OMD[mattiols]:~$ python3
Python 3.8.7 (default, Feb  3 2021, 03:02:50) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>
```
Check_MK version is 2.0.0p13

```
OMD[mattiols]:~$ cmk --version
This is Check_MK version 2.0.0p13 CRE
```

![image](https://user-images.githubusercontent.com/5707570/140551040-4cc1d995-b779-4700-beed-7eca70d721e9.png)

Other debug:
```
OMD[mattiols]:~$ cmk -R --debug
Generating configuration for core (type nagios)...Found '%s' in service description (Host: shelly-cucina, Check plugin: shelly_power, Item: None). Please try to rediscover the service to fix this issue.
Traceback (most recent call last):
  File "/omd/sites/mattiols/bin/cmk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/mattiols/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/mattiols/lib/python3/cmk/base/modes/check_mk.py", line 1152, in mode_restart
    cmk.base.core.do_restart(create_core(config.monitoring_core))
  File "/omd/sites/mattiols/lib/python3/cmk/base/core.py", line 59, in do_restart
    core_config.do_create_config(core)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_config.py", line 336, in do_create_config
    _create_core_config(core)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_config.py", line 401, in _create_core_config
    core.create_config(helper_config.serial)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_nagios.py", line 69, in create_config
    self._create_core_config()
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_nagios.py", line 82, in _create_core_config
    create_config(config_buffer, hostnames=None)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_nagios.py", line 153, in create_config
    _create_nagios_config_host(cfg, config_cache, hostname)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_nagios.py", line 184, in _create_nagios_config_host
    _create_nagios_servicedefs(cfg, config_cache, hostname, host_attrs)
  File "/omd/sites/mattiols/lib/python3/cmk/base/core_nagios.py", line 319, in _create_nagios_servicedefs
    host_check_table = get_check_table(hostname)
  File "/omd/sites/mattiols/lib/python3/cmk/base/check_table.py", line 177, in get_check_table
    host_check_table = HostCheckTable(
  File "/omd/sites/mattiols/lib/python3/cmk/base/check_table.py", line 53, in __init__
    for service in self._get_static_check_entries(config_cache, host_config)
  File "/omd/sites/mattiols/lib/python3/cmk/base/check_table.py", line 75, in _get_static_check_entries
    descr = config.service_description(host_config.hostname, check_plugin_name, item)
  File "/omd/sites/mattiols/lib/python3/cmk/base/config.py", line 1089, in service_description
    raise MKGeneralException(
cmk.utils.exceptions.MKGeneralException: Found '%s' in service description (Host: shelly-cucina, Check plugin: shelly_power, Item: None). Please try to rediscover the service to fix this issue.
```

**Comment by matoH12** [comment]
Ok so do you have set this parameters  "Custom SHEELY meter name" in effective parameters ?   


![obrázok](https://user-images.githubusercontent.com/63114658/140561160-9d819f91-7544-4750-b33f-4b557c54aefd.png)

Im try install Check_mk CRE P13 and plugin works fine. You can try remove HOST and create new host with another name. What version of shelly plugin you have install ?

**Comment by andrea-mattioli** [comment]
Hi, sorry for the delay but i wasn't at home for the weekend!
i've installed the latest 1.1 plugin version.

![image](https://user-images.githubusercontent.com/5707570/140705973-9fa9f9c5-eb20-474f-884c-d6d6735bcd09.png)

I removed the host and change the service as you ask, then i've recrated host and recreate an eforced service, i don't have the previous error but i can't see any service on my shelly host.

**Comment by matoH12** [comment]
It is crazy bug :D . If you can try download agent output you are see shelly shelly_power value ? 

![obrázok](https://user-images.githubusercontent.com/63114658/140809823-09d6627c-da1d-4a83-ae40-a45deb540883.png)

**Comment by andrea-mattioli** [comment]
Hi, the agent output is empty, your host elektromer has configured with agent or api?

![image](https://user-images.githubusercontent.com/5707570/140884186-fe089b5e-5521-42be-b86e-a8a57e2f4ffd.png)

**Comment by andrea-mattioli** [comment]
OMD[mattiols]:/tmp$ /omd/sites/mattiols/local/share/check_mk/agents/special/agent_shelly_power  -u 'asd' -p 'asd' -n 'asd' --no-cert-check '192.168.1.105'
/usr/bin/env: ‘python’: No such file or directory

I've changed python to python3 and it works fine!! this is the bug :D 

Trying to acquire lock on /omd/sites/mattiols/var/check_mk/autochecks/shelly-cucina.mk
Got lock on /omd/sites/mattiols/var/check_mk/autochecks/shelly-cucina.mk
Releasing lock on /omd/sites/mattiols/var/check_mk/autochecks/shelly-cucina.mk
Released lock on /omd/sites/mattiols/var/check_mk/autochecks/shelly-cucina.mk
 16 shelly_power
SUCCESS - Found 16 services, no host labels

thanks for your support!
